### ISSUE TITLE
BAT File is not working properly

### ISSUE THREAD

**Issue by ertanturan** [SimBlocks/OneWorldSDKforUnity#11] opened 2021-11-22 15:05 UTC
The correct bat should be like this : 
pathFrom variable looks into a wrong directory.. 
``` csharp 


set currentDir=%cd%
set "pathFrom=%~dp0src\Bin\"
set "pathTo=%~dp0src\OneWorldSDK_UnityDemo\Assets\Plugins\"

REM COPY DEPENDENCIES
copy /y "%pathFrom%Newtonsoft.Json.dll" "%pathTo%"
copy /y "%pathFrom%Pngcs.dll" "%pathTo%"
copy /y "%pathFrom%gdal_csharp.dll" "%pathTo%"
copy /y "%pathFrom%BitMiracle.LibJpeg.NET.dll" "%pathTo%"
copy /y "%pathFrom%ogr_csharp.dll" "%pathTo%"
copy /y "%pathFrom%x86\SQLite.Interop.dll" "%pathTo%windows-x86\"
copy /y "%pathFrom%x64\SQLite.Interop.dll" "%pathTo%windows-x64\"
copy /y "%pathFrom%DotSpatial.Projections.dll" "%pathTo%"
copy /y "%pathFrom%osr_csharp.dll" "%pathTo%"
copy /y "%pathFrom%OsmSharp.dll" "%pathTo%"
copy /y "%pathFrom%OsmSharp.dll" "%pathTo%"
copy /y "%pathFrom%Npgsql.dll" "%pathTo%"
copy /y "%pathFrom%..\src\Libraries\packages\protobuf-net.2.3.7\lib\net40\protobuf-net.dll" "%pathTo%"
copy /y "%pathFrom%NetTopologySuite.dll" "%pathTo%"
copy /y "%pathFrom%BruTile.dll" "%pathTo%"
copy /y "%pathFrom%Microsoft.Bcl.AsyncInterfaces.dll" "%pathTo%"
copy /y "%pathFrom%Npgsql.dll" "%pathTo%"

copy /y "%pathFrom%System.*.dll" "%pathTo%"
del "%pathTo%System.Net.Http.dll"

copy /y "%pathFrom%sbioMath.dll" "%pathTo%"
copy /y "%pathFrom%sbioMath.pdb" "%pathTo%"

copy /y "%pathFrom%sbioOneWorldSDK.dll" "%pathTo%"

REM CONVERT PDBs TO MDBs
cd %pathFrom%
pdb2mdb.exe sbioOneWorldSDK.dll
pdb2mdb.exe sbioMath.dll
cd %currentDir%

copy /y "%pathFrom%sbioOneWorldSDK.dll.mdb" "%pathTo%"
copy /y "%pathFrom%sbioMath.dll.mdb" "%pathTo%"
pause
```

**Comment by SimBlocks** [comment] 2021-11-22 22:29
When you build **src\Libraries\OneWorldSDK.sln**, do the binaries output to **bin** or **src\bin** for you?

**Comment by ertanturan** [comment] 2021-11-23 10:28
> When you build **src\Libraries\OneWorldSDK.sln**, do the binaries output to **bin** or **src\bin** for you?

The output folder been created to the `src\bin` for me..

**Comment by SimBlocks** [comment] 2021-11-23 19:27
Ok. I think the problem is that the Release configuration output path does not match the Debug configuration path.

**Comment by SimBlocks** [comment] 2022-01-07 04:01
Closing this issue.

**Closed** 2022-01-07 04:00 UTC
